"""user column revised and added

Revision ID: 17ea7acd770d
Revises: 03956fc409f1
Create Date: 2025-03-16 21:14:43.635723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ea7acd770d'
down_revision: Union[str, None] = '03956fc409f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_column('users', 'role')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
