"""user model init

Revision ID: 9eeda1edd26c
Revises: 
Create Date: 2025-03-19 10:38:09.544123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eeda1edd26c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='인덱스'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='이메일'),
    sa.Column('password', sa.String(length=100), nullable=True, comment='비밀번호'),
    sa.Column('name', sa.String(length=20), nullable=True, comment='이름'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일'),
    sa.Column('delete_at', sa.DateTime(), nullable=True, comment='삭제일'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
