"""user, project, user_project added

Revision ID: bc0d175d9398
Revises: 
Create Date: 2025-03-21 16:55:12.094744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0d175d9398'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='인덱스'),
    sa.Column('name', sa.String(length=20), nullable=True, comment='이름'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일'),
    sa.Column('delete_at', sa.DateTime(), nullable=True, comment='삭제일'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='인덱스'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='이메일'),
    sa.Column('password', sa.String(length=100), nullable=True, comment='비밀번호'),
    sa.Column('name', sa.String(length=20), nullable=True, comment='이름'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일'),
    sa.Column('delete_at', sa.DateTime(), nullable=True, comment='삭제일'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('user_project',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='인덱스'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='인덱스'),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='인덱스'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='역할'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.PrimaryKeyConstraint('id'),
    comment='유저'
    )
    op.create_index(op.f('ix_user_project_project_id'), 'user_project', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_project_user_id'), 'user_project', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_project_user_id'), table_name='user_project')
    op.drop_index(op.f('ix_user_project_project_id'), table_name='user_project')
    op.drop_table('user_project')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ###
