"""some table_args added about user, project, user_project

Revision ID: f487cc8c08ff
Revises: bc0d175d9398
Create Date: 2025-03-21 16:57:38.900032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f487cc8c08ff'
down_revision: Union[str, None] = 'bc0d175d9398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'project',
        '프로젝트',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'user',
        '유저',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(None, 'user_project', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_project', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'user_project',
        '유저 프로젝트 관계 테이블',
        existing_comment='유저',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user_project',
        '유저',
        existing_comment='유저 프로젝트 관계 테이블',
        schema=None
    )
    op.drop_constraint(None, 'user_project', type_='foreignkey')
    op.drop_constraint(None, 'user_project', type_='foreignkey')
    op.drop_table_comment(
        'user',
        existing_comment='유저',
        schema=None
    )
    op.drop_table_comment(
        'project',
        existing_comment='프로젝트',
        schema=None
    )
    # ### end Alembic commands ###
